baseURL = "https://engineering-managers.github.io/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Engineering Managers reading list"
theme = "hugo-theme-learn"
[outputs]
home = [ "HTML", "RSS", "JSON"]
