baseURL = "https://engineering-managers.github.io"
languageCode = "en-us"
title = "Engineering Managers reading list"
theme = "hugo-theme-learn"
relativeURLs = true
[outputs]
home = [ "HTML", "RSS", "JSON"]
